### ISSUE TITLE
字體有版權存疑！

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [z01font/ZoomlaCusong#1]
但一看就是抄襲漢儀綜藝體的，建議不能商用！

**Comment by z01font** [comment]
> 但一看就是抄襲漢儀綜藝體的，建議不能商用！

上士闻道，勤而行之。
你可以说XX与XX字体近似，但不应将抄袭二字简单的扣在人家头上。
又或者说：你为什么不说，这款字的原作出自何处？

这有一些信息，你可以去浏览访问：
http://v.ziti163.com
http://f.ziti163.com

**Comment by UltimateAmitieKaiNiC** [comment]
https://www.maoken.com/zhengyi/10419.html
