### ISSUE TITLE
字体盗版版权存疑｜Illegal modification of font, copyright infringement

### ISSUE THREAD

**Issue by NightFurySL2001** [z01font/ZoomlaCusong#2]
此字体明显由收费字体（[方正综艺](http://www.foundertype.com/index.php/FontInfo/index/id/178.html)）所改造而来，附图给上本仓库的图片与方正综艺对比：  
This font is obviously modified from a paid font ([FounderType Zhongyi](http://www.foundertype.com/index.php/FontInfo/index/id/178.html)), and the following picures shows comparison of the pictures in this repository compared with FounderType Zhongyi:

【红、黄色为方正综艺】［Red/Yellow text are from FounderType Zhongyi］
![image](https://user-images.githubusercontent.com/33471049/111419897-3523a400-8725-11eb-8814-5e1c5a502bfa.png)
![image](https://user-images.githubusercontent.com/33471049/111418918-7ca93080-8723-11eb-82cf-63095d7b7122.png)

本仓库宣称使用 [SIL 开源字型授权](http://scripts.sil.org/OFL)，但是明显是由收费字体改造而来。如果贵方仍固执己我，请问贵方是在转嫁非法盗版字体，并且修改字体的罪名给使用者吗？  
This repository says to be using [SIL Open Font License](http://scripts.sil.org/OFL), however it is very clear that the font is modified from a paid font. May I ask if z01font is transferring the charge of illegal use of and modification of font to the end users?

**Comment by z01font** [comment]
# 致歉

2021年3月15日，逐浪字库团队收到“猫啃maoken"社区的馈，标题“逐浪粗宋：逐浪字库团队出品粗宋字体 版权存疑 不建议商用”。

同时给予邮件通知，在此，我们在进行复核的基础上，对此申明：

1、逐浪粗宋确为我方原创，我们开源包中提供了包括矢量、点阵、TTF、OTF全部创作源。

2、逐浪粗宋严格遵守版权，只有原创与钻研才能获得社会的尊重与认同。

3、逐浪粗宋，是我们创业团队的早期作品，在创作一款字体的过程中，既涉及管理问题，又涉及创作理念，前期应该有较多的学习、描摹、参照、甚至是不自主的沿袭使用，或如同互联网行业创作雷同事例--但不管是否雷同或是更加严厉的批评，我们都认为这是对我们的关爱和支持，在此我们深表感谢，感谢开源社区、社会公众对我们的批评、鞭策，这是我们成长的基石。

4、为了表示我们的道歉诚意，我们将于未来一个月内提供新作，贡献于开源社区，并保持此致歉函，同时更加注重聆听社会声音。



--逐浪字体z01font

2021-3-17 6:58

**Comment by NightFurySL2001** [comment]
谨此要求贵方立即撤回 SIL 开源字型授权的声明并选择使用个人非商业使用授权或者下架本字体仓库；否则请提供证据确保最终用户不会因使用逐浪粗宋而受到法律对付。贵方的源文件与[方正综艺](http://www.foundertype.com/index.php/FontInfo/index/id/178.html)十分接近，无法变成法律上的保护证据。

I would have to request z01font to immediately retract your statement of SIL Open Font License and either changing the license to a personal non-commercial use license, or removing this font repository. If not, please provide any evidence to ensure that the end users will not be taken action against for-profit font foundries. The source files provided in this repository is very similar to [FounderType Zhongyi](http://www.foundertype.com/index.php/FontInfo/index/id/178.html) and can not be legal evidence in court.
